### ISSUE TITLE
Help How To run

### ISSUE THREAD

**Issue by fastplay80** [HHousen/DocSum#4]
hello,sorry if i use this space but i am very newbie whitout code knowledge
Is possible run on my local pc whit anaconda or ubutu or better whit google collab?

**Comment by HHousen** [comment]
Yes, DocSum will run with anaconda on Ubuntu perfectly (that is the recommended setup), just follow the [installation instructions](https://github.com/HHousen/DocSum#installation). I just created a google colab file that demonstrates the functionality of `cmd_summarizer.py`. You can view it here: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hhousen/docsum/blob/master/DocSum.ipynb).
