### ISSUE TITLE
Train the sum-model with my own data

### ISSUE THREAD

**Issue by zhongxiangboy** [HHousen/DocSum#7]
How can I train the sum-model based on BART with my own dataset?

**Comment by HHousen** [comment]
@zhongxiangboy To train your own BART models you can use my other project, [HHousen/TransformerSum](https://github.com/HHousen/TransformerSum), on GitHub. You can find tutorials and documentation on [Read The Docs](https://transformersum.readthedocs.io/en/latest/). Alternatively, you can try the [seq2seq example](https://github.com/huggingface/transformers/tree/master/examples/seq2seq) in the [huggingface/transformers](https://github.com/huggingface/transformers) repository.
